server:
  port: 8081
  servlet:
    context-path: /activity
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.114.122.147/activiti?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
